MedicineTrackingSystem/Models/BaseEntity.cs
namespace Pharmacy.Models
{
    public class BaseEntity
    {
        public int Id { get; set; }
    }
}

MedicineTrackingSystem/Models/DTO/MedicineName.cs
namespace Pharmacy.Models.DTO
{
    public class MedicineName
    {
        public int Id { get; set; }
        public string Name { get; set; }
    }
}

MedicineTrackingSystem/Models/DTO/PrescriptionNumber.cs
namespace Pharmacy.Models.DTO
{
    public class PrescriptionNumber
    {
        public int Id { get; set; }
        public string Number { get; set; }
    }
}

MedicineTrackingSystem/Models/Medicine.cs
using System.ComponentModel.DataAnnotations;

namespace Pharmacy.Models
{
    public class Medicine : BaseEntity
    {
        [Required(ErrorMessage = "Medicine's name is required")]
        [Display(Name = "Name")]
        [StringLength(100,ErrorMessage = "Medicine's name is too long")]
        public string Name { get; set; }

        [Required(ErrorMessage = "Brand's name is required")]
        [Display(Name = "Brand")]
        [StringLength(100, ErrorMessage = "Brand's name is too long")]
        public string Brand { get; set; }

        [Required(ErrorMessage = "Price is required")]
        [Display(Name = "Price")]
        [RegularExpression(@"\d+(\.\d{1,2})?", ErrorMessage = "Invalid price")]
        public double Price { get; set; }

        [Required(ErrorMessage = "Amount is required")]
        [Display(Name = "Amount")]
        public int Amount { get; set; }

        [Required(ErrorMessage = "It is required")]
        [Display(Name = "ExpiryDate")]
        public string ExpiryDate { get; set; }

    }
}

MedicineTrackingSystem/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace Pharmacy.Controllers
{
    public class HomeController : Controller
    {
        public async Task<IActionResult> Index() => await Task.Run(() => View());
    }
}

MedicineTrackingSystem/Controllers/MedicineController.cs
using Microsoft.AspNetCore.Mvc;
using Pharmacy.Models;
using System.Linq;
using System.Threading.Tasks;

namespace Pharmacy.Controllers
{
   
    public class MedicineController : Controller
    {

        [HttpGet]
        //public async Task<IActionResult> Index() => View((await _medicineService.GetAllMedicinesAsync()).OrderBy(m => m.Id));

        [HttpGet]
        public async Task<IActionResult> Create() => await Task.Run(() => View());

        //[HttpPost]
        //public async Task<IActionResult> Create(Medicine medicine)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        await _medicineService.AddMedicineAsync(medicine);
        //        return RedirectToAction(nameof(Index));
        //    }
        //    return View(medicine);
        //}

        //[HttpGet]
        //public async Task<IActionResult> Edit(int medicineId) =>
        //    await _medicineService.GetMedicineByIdAsync(medicineId) is var medicine == null
        //        ? (IActionResult)NotFound()
        //        : View(medicine);

        //[HttpPost]
        //public async Task<IActionResult> Edit(Medicine medicine)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        await _medicineService.EditMedicineAsync(medicine);
        //        return RedirectToAction(nameof(Index));
        //    }
        //    return View(medicine);
        //}


    }

}

MedicineTrackingSystem/Views/Home/Index.cshtml
<h1 class="col-md-offset-2 col-md-8 ">Pharmacy</h1>
<div class="thumbnail col-md-offset-2 col-md-8 .caption">
    <h4>What would you like to do?</h4>
    <div>
        <a asp-controller="Medicine" asp-action="Index" class="list-group-item">Check list of medicines, add, edit or delete medicine </a>
        <a asp-controller="Prescription" asp-action="Index" class="list-group-item"> Check list of prescriptions, add or delete prescription </a>
        <a asp-controller="Order" asp-action="Index" class="list-group-item"> Check list of orders or place an order </a>
    </div>
</div>

MedicineTrackingSystem/Views/Medicine/Create.cshtml
@model Pharmacy.Models.Medicine

<h2>Add a medicine</h2>
<hr/>
<div class="thumbnail col-md-offset-3 col-md-6">
    <form asp-action="Create">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
           
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Amount" class="control-label"></label>
                <input asp-for="Amount" class="form-control" />
                <span asp-validation-for="Amount" class="text-danger"></span>

            </div>
            
            <div class="form-group">
                <input type="submit" value="Add medicine" class="btn btn-success mt-30 pull-right" />
                <a asp-action="Index" class="btn btn-danger mt-30">Back</a>
            </div>
    </form>
</div>

MedicineTrackingSystem/Views/Medicine/Edit.cshtml
@model Pharmacy.Models.Medicine

<h2>Edit Medicine</h2>
<hr/>
<div class="row">
    <form asp-action="Edit">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <input type="hidden" asp-for="Id" />
        <div class="col-md-4">
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
           
            <div class="form-group">
                <label asp-for="Amount" class="control-label"></label>
                <input asp-for="Amount" class="form-control" />
                <span asp-validation-for="Amount" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
          
            <div class="form-group">
                <input type="submit" value="Edit medicine" class="btn btn-success" style="margin-top:30px" />
                <a asp-action="Index" class="btn btn-danger pull-right" style="margin-top:30px">Back</a>
            </div>
        </div>
    </form>
</div>

MedicineTrackingSystem/Views/Medicine/Index.cshtml
@model IEnumerable<Pharmacy.Models.Medicine>

<div class="pull-left">
    <h2>Medicines</h2>
</div>
    <table class="table" style="background-color: azure">
        <thead>
        <tr>
            <th>Name</th>
            <th>Manufacturer</th>
            <th>Amount</th>
            <th>With prescription</th>
            <th>Price</th>
            <th>
                <a asp-action="Create" class="btn btn-danger btn-sm">Add new medicine</a>
            </th>
        </tr>
        </thead>
    <tbody>
    @foreach (var medicine in Model)
    {
        <tr>
            <td>@Html.DisplayFor(model => medicine.Name)</td>
            <td>@Html.DisplayFor(model => medicine.Amount)</td>
            <td>@Html.Raw(medicine.Price.ToString("c"))</td>
            <td>
                <a asp-action="Edit" asp-route-medicineId="@medicine.Id">Edit</a>
                <a asp-action="Delete" asp-route-medicineId="@medicine.Id">Delete</a>
            </td>
                
        </tr>
    }
    </tbody>
    </table>

MedicineTrackingSystem/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link href="~/lib/bootstrap/dist/css/bootstrap.css" rel="stylesheet" />
    <link href="~/content/site.css" rel="stylesheet" />
    <link href="https://fonts.googleapis.com/css?family=Roboto&display=swap" rel="stylesheet">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <title>@ViewBag.Title</title>
</head>
<body>
<nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li>
                    <a asp-controller="Home" asp-action="Index" class="navbar-brand">
                        <img src="~/images/LogoIcon.png" title="logo" style="display: inline-block; height: 150%" />
                        <span style="display: inline-block">Pharmacy</span>
                    </a>
                </li>
                
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <li>
                    <a asp-controller="Medicine" asp-action="Index" class="navbar-brand" >Medicines</a>
                </li>
                <li>
                    <a asp-controller="Prescription" asp-action="Index" class="navbar-brand">Prescriptions</a>
                </li>
                <li>
                    <a asp-controller="Order" asp-action="Index" class="navbar-brand navbar-brand">Orders</a>
                </li>
            </ul>
        </div>
    </div>
</nav>
<div class="container body-content">
    <div class="row">
        @RenderBody()
    </div>
</div>
</body>
</html>